# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /bin/cmake

# The command to remove a file.
RM = /bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/codes/ElectronSourceCalibration

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/codes/ElectronSourceCalibration

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/codes/ElectronSourceCalibration/CMakeFiles /root/codes/ElectronSourceCalibration/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/codes/ElectronSourceCalibration/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ElectronSrcCal

# Build rule for target.
ElectronSrcCal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ElectronSrcCal
.PHONY : ElectronSrcCal

# fast build rule for target.
ElectronSrcCal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/build
.PHONY : ElectronSrcCal/fast

ElectronSrcCal.o: ElectronSrcCal.cc.o

.PHONY : ElectronSrcCal.o

# target to build an object file
ElectronSrcCal.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/ElectronSrcCal.cc.o
.PHONY : ElectronSrcCal.cc.o

ElectronSrcCal.i: ElectronSrcCal.cc.i

.PHONY : ElectronSrcCal.i

# target to preprocess a source file
ElectronSrcCal.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/ElectronSrcCal.cc.i
.PHONY : ElectronSrcCal.cc.i

ElectronSrcCal.s: ElectronSrcCal.cc.s

.PHONY : ElectronSrcCal.s

# target to generate assembly for a file
ElectronSrcCal.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/ElectronSrcCal.cc.s
.PHONY : ElectronSrcCal.cc.s

src/MyActionInitialization.o: src/MyActionInitialization.cc.o

.PHONY : src/MyActionInitialization.o

# target to build an object file
src/MyActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyActionInitialization.cc.o
.PHONY : src/MyActionInitialization.cc.o

src/MyActionInitialization.i: src/MyActionInitialization.cc.i

.PHONY : src/MyActionInitialization.i

# target to preprocess a source file
src/MyActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyActionInitialization.cc.i
.PHONY : src/MyActionInitialization.cc.i

src/MyActionInitialization.s: src/MyActionInitialization.cc.s

.PHONY : src/MyActionInitialization.s

# target to generate assembly for a file
src/MyActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyActionInitialization.cc.s
.PHONY : src/MyActionInitialization.cc.s

src/MyDetectorConstruction.o: src/MyDetectorConstruction.cc.o

.PHONY : src/MyDetectorConstruction.o

# target to build an object file
src/MyDetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyDetectorConstruction.cc.o
.PHONY : src/MyDetectorConstruction.cc.o

src/MyDetectorConstruction.i: src/MyDetectorConstruction.cc.i

.PHONY : src/MyDetectorConstruction.i

# target to preprocess a source file
src/MyDetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyDetectorConstruction.cc.i
.PHONY : src/MyDetectorConstruction.cc.i

src/MyDetectorConstruction.s: src/MyDetectorConstruction.cc.s

.PHONY : src/MyDetectorConstruction.s

# target to generate assembly for a file
src/MyDetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyDetectorConstruction.cc.s
.PHONY : src/MyDetectorConstruction.cc.s

src/MyDetectorMessenger.o: src/MyDetectorMessenger.cc.o

.PHONY : src/MyDetectorMessenger.o

# target to build an object file
src/MyDetectorMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyDetectorMessenger.cc.o
.PHONY : src/MyDetectorMessenger.cc.o

src/MyDetectorMessenger.i: src/MyDetectorMessenger.cc.i

.PHONY : src/MyDetectorMessenger.i

# target to preprocess a source file
src/MyDetectorMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyDetectorMessenger.cc.i
.PHONY : src/MyDetectorMessenger.cc.i

src/MyDetectorMessenger.s: src/MyDetectorMessenger.cc.s

.PHONY : src/MyDetectorMessenger.s

# target to generate assembly for a file
src/MyDetectorMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyDetectorMessenger.cc.s
.PHONY : src/MyDetectorMessenger.cc.s

src/MyEventAction.o: src/MyEventAction.cc.o

.PHONY : src/MyEventAction.o

# target to build an object file
src/MyEventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyEventAction.cc.o
.PHONY : src/MyEventAction.cc.o

src/MyEventAction.i: src/MyEventAction.cc.i

.PHONY : src/MyEventAction.i

# target to preprocess a source file
src/MyEventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyEventAction.cc.i
.PHONY : src/MyEventAction.cc.i

src/MyEventAction.s: src/MyEventAction.cc.s

.PHONY : src/MyEventAction.s

# target to generate assembly for a file
src/MyEventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyEventAction.cc.s
.PHONY : src/MyEventAction.cc.s

src/MyPhysicsList.o: src/MyPhysicsList.cc.o

.PHONY : src/MyPhysicsList.o

# target to build an object file
src/MyPhysicsList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyPhysicsList.cc.o
.PHONY : src/MyPhysicsList.cc.o

src/MyPhysicsList.i: src/MyPhysicsList.cc.i

.PHONY : src/MyPhysicsList.i

# target to preprocess a source file
src/MyPhysicsList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyPhysicsList.cc.i
.PHONY : src/MyPhysicsList.cc.i

src/MyPhysicsList.s: src/MyPhysicsList.cc.s

.PHONY : src/MyPhysicsList.s

# target to generate assembly for a file
src/MyPhysicsList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyPhysicsList.cc.s
.PHONY : src/MyPhysicsList.cc.s

src/MyPrimaryGeneratorAction.o: src/MyPrimaryGeneratorAction.cc.o

.PHONY : src/MyPrimaryGeneratorAction.o

# target to build an object file
src/MyPrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyPrimaryGeneratorAction.cc.o
.PHONY : src/MyPrimaryGeneratorAction.cc.o

src/MyPrimaryGeneratorAction.i: src/MyPrimaryGeneratorAction.cc.i

.PHONY : src/MyPrimaryGeneratorAction.i

# target to preprocess a source file
src/MyPrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyPrimaryGeneratorAction.cc.i
.PHONY : src/MyPrimaryGeneratorAction.cc.i

src/MyPrimaryGeneratorAction.s: src/MyPrimaryGeneratorAction.cc.s

.PHONY : src/MyPrimaryGeneratorAction.s

# target to generate assembly for a file
src/MyPrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyPrimaryGeneratorAction.cc.s
.PHONY : src/MyPrimaryGeneratorAction.cc.s

src/MyRunAction.o: src/MyRunAction.cc.o

.PHONY : src/MyRunAction.o

# target to build an object file
src/MyRunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyRunAction.cc.o
.PHONY : src/MyRunAction.cc.o

src/MyRunAction.i: src/MyRunAction.cc.i

.PHONY : src/MyRunAction.i

# target to preprocess a source file
src/MyRunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyRunAction.cc.i
.PHONY : src/MyRunAction.cc.i

src/MyRunAction.s: src/MyRunAction.cc.s

.PHONY : src/MyRunAction.s

# target to generate assembly for a file
src/MyRunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyRunAction.cc.s
.PHONY : src/MyRunAction.cc.s

src/MySteppingAction.o: src/MySteppingAction.cc.o

.PHONY : src/MySteppingAction.o

# target to build an object file
src/MySteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MySteppingAction.cc.o
.PHONY : src/MySteppingAction.cc.o

src/MySteppingAction.i: src/MySteppingAction.cc.i

.PHONY : src/MySteppingAction.i

# target to preprocess a source file
src/MySteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MySteppingAction.cc.i
.PHONY : src/MySteppingAction.cc.i

src/MySteppingAction.s: src/MySteppingAction.cc.s

.PHONY : src/MySteppingAction.s

# target to generate assembly for a file
src/MySteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MySteppingAction.cc.s
.PHONY : src/MySteppingAction.cc.s

src/MyTrackingAction.o: src/MyTrackingAction.cc.o

.PHONY : src/MyTrackingAction.o

# target to build an object file
src/MyTrackingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyTrackingAction.cc.o
.PHONY : src/MyTrackingAction.cc.o

src/MyTrackingAction.i: src/MyTrackingAction.cc.i

.PHONY : src/MyTrackingAction.i

# target to preprocess a source file
src/MyTrackingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyTrackingAction.cc.i
.PHONY : src/MyTrackingAction.cc.i

src/MyTrackingAction.s: src/MyTrackingAction.cc.s

.PHONY : src/MyTrackingAction.s

# target to generate assembly for a file
src/MyTrackingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ElectronSrcCal.dir/build.make CMakeFiles/ElectronSrcCal.dir/src/MyTrackingAction.cc.s
.PHONY : src/MyTrackingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ElectronSrcCal"
	@echo "... ElectronSrcCal.o"
	@echo "... ElectronSrcCal.i"
	@echo "... ElectronSrcCal.s"
	@echo "... src/MyActionInitialization.o"
	@echo "... src/MyActionInitialization.i"
	@echo "... src/MyActionInitialization.s"
	@echo "... src/MyDetectorConstruction.o"
	@echo "... src/MyDetectorConstruction.i"
	@echo "... src/MyDetectorConstruction.s"
	@echo "... src/MyDetectorMessenger.o"
	@echo "... src/MyDetectorMessenger.i"
	@echo "... src/MyDetectorMessenger.s"
	@echo "... src/MyEventAction.o"
	@echo "... src/MyEventAction.i"
	@echo "... src/MyEventAction.s"
	@echo "... src/MyPhysicsList.o"
	@echo "... src/MyPhysicsList.i"
	@echo "... src/MyPhysicsList.s"
	@echo "... src/MyPrimaryGeneratorAction.o"
	@echo "... src/MyPrimaryGeneratorAction.i"
	@echo "... src/MyPrimaryGeneratorAction.s"
	@echo "... src/MyRunAction.o"
	@echo "... src/MyRunAction.i"
	@echo "... src/MyRunAction.s"
	@echo "... src/MySteppingAction.o"
	@echo "... src/MySteppingAction.i"
	@echo "... src/MySteppingAction.s"
	@echo "... src/MyTrackingAction.o"
	@echo "... src/MyTrackingAction.i"
	@echo "... src/MyTrackingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

